export const SET_DISPLAYED_POSTS_REQUEST = 'SET_DISPLAYED_POSTS_REQUEST';
export const SET_DISPLAYED_POSTS = 'SET_DISPLAYED_POSTS';
export const SET_SEARCH = 'SET_SEARCH';
export const SET_SORT = 'SET_SORT';
